---
title: "The Evolution of the World Cup"
subtitle: "STA/ISS 313 - Project 1"
author: "Team Messi"
format: html
editor: visual
---

## Abstract

(1 paragraph): Project abstract.

------------------------------------------------------------------------

## Introduction

(1-2 paragraphs): Brief introduction to the dataset. You may repeat some of the information about the dataset provided in the introduction to the dataset on the TidyTuesday repository, paraphrasing on your own terms. Imagine that your project is a standalone document and the grader has no prior knowledge of the dataset.

## Question 1: The Effect of New Rules on Goals Scored

### Introduction

Throughout the World Cup's history, many new rules and technologies have been implemented, changing the way soccer is played. This includes the introduction of penalties for tie breaking, VAR to contest calls on the field, increasing the number of teams in each World Cup, and many more. These factors affect how teams play and have forced players to adapt their strategies. In order to assess the impact caused to the overall game, the most straightforward metric to consider is the number of goals scored. Although the score can oversimplify a very complex game, many important decisions are made from it, including which countries make it into the World Cup and ultimately win the tournament. We, as soccer fans, have decided to analyze goals because it is unarguably the most important and entertaining part of the game.

To explore our question, we will be using the `wcmatches` and `worldcups` datasets from TidyTuesday, and merging in external data from Kaggle containing specifics into penalty kicks taken during the World Cups. Specifically, we will be looking at the variables with year, goals per game, penalties awarded and penalties scored, as well as created variables indicating the implementation of a new rule or a notable event. We will be analyzing both the broad concept of total goals scored as well as penalty kicks. Penalties are a very controversial and powerful part of soccer. For perspective, 3 World Cup finals have been decided by penalty shootouts. To see how the game has been affected since the introduction of penalties in 1970, we will be analyzing the number of penalties awarded and scored over time. This, in conjunction with the rules implemented, will give us insight into how penalties have affected scores and how players have adapted to the changing rules.

### Approach

(1-2 paragraphs): Describe what types of plots you are going to make to address your question. For each plot, provide a clear explanation as to why this plot (e.g. boxplot, barplot, histogram, etc.) is best for providing the information you are asking about. The two plots should be of different types, and at least one of the two plots needs to use either color mapping or facets.

For the first plot, we will be making a scatterplot showing the goals scored per game during each World Cup. This will make any trends over time very visible and allow for our annotations, which will hopefully reveal more information. We are going to indicate years, using the shape and color of points, in which a new rule or notable event occurred and provide a brief description. Through this, we hope to provide reasoning for long and short-term trends in the plot.

### Analysis

(2-3 code blocks, 2 figures, text/code comments as needed): In this section, provide the code that generates your plots. Use scale functions to provide nice axis labels and guides. You are welcome to use theme functions to customize the appearance of your plot, but you are not required to do so. All plots must be made with **ggplot2**. Do not use base R or lattice plotting functions.

### Discussion

(1-3 paragraphs): In the Discussion section, interpret the results of your analysis. Identify any trends revealed (or not revealed) by the plots. Speculate about why the data looks the way it does.

## Question 2: Title that relates to the question you're answering

### Introduction

(1-2 paragraphs): Introduction to the question and what parts of the dataset are necessary to answer the question. Also discuss why you're interested in this question.

### Approach

(1-2 paragraphs): Describe what types of plots you are going to make to address your question. For each plot, provide a clear explanation as to why this plot (e.g. boxplot, barplot, histogram, etc.) is best for providing the information you are asking about. The two plots should be of different types, and at least one of the two plots needs to use either color mapping or facets.

### Analysis

(2-3 code blocks, 2 figures, text/code comments as needed): In this section, provide the code that generates your plots. Use scale functions to provide nice axis labels and guides. You are welcome to use theme functions to customize the appearance of your plot, but you are not required to do so. All plots must be made with **ggplot2**. Do not use base R or lattice plotting functions.

### Discussion

(1-3 paragraphs): In the Discussion section, interpret the results of your analysis. Identify any trends revealed (or not revealed) by the plots. Speculate about why the data looks the way it does.
